### ISSUE TITLE
用autojs能实现自动炼草吗

### ISSUE THREAD

**Issue by lgjhkd** [NateScarlet/auto-dragalia#1]

**Comment by NateScarlet** [comment]
啥叫炼草...

**Comment by lgjhkd** [comment]
反复刷金币本，直到出稀有怪，打死掉幸运草

**Comment by NateScarlet** [comment]
如果不要不出稀有怪就提前放弃省体力功能的话 用重复单人战斗就行 

要提前放弃的话需要
- [ ] 识别记录稀有怪的图标出现过没 
- [ ] 读取boss图后没出现过稀有怪就直接放弃

得另写一个任务 有空试试

**Comment by NateScarlet** [comment]
0.6.0 已实现
