### ISSUE TITLE
刷稀有好像还是没什么用

### ISSUE THREAD

**Issue by nudgee28** [NateScarlet/auto-dragalia#10]
金币本，刷草，每次都是判定成功刷到。。其实没

**Comment by NateScarlet** [comment]
逻辑是找不到稀有物品数量为0 就认为是刷到了 

之前相似设成0.97都会把刷到认为没刷到  现在是0.99 在我这准确是很高

你发下你战斗菜单界面截图我换成你的图试试

**Comment by youmei** [comment]
你是不是用了低画质模式？图片是高画质下截取的，低画质下永远会判断没匹配到【稀有掉落*0】这张图，所以就认为你刷到了稀有

**Comment by NateScarlet** [comment]
或者你把你的这个图发一个上来 我加一个或判断就行了

**Comment by NateScarlet** [comment]
> 
> 
> 你是不是用了低画质模式？图片是高画质下截取的，低画质下永远会判断没匹配到【稀有掉落*0】这张图，所以就认为你刷到了稀有

画质应该不影响二维的 UI

应该是分辨率不同导致的

**Comment by youmei** [comment]
> 
> 
> > 你是不是用了低画质模式？图片是高画质下截取的，低画质下永远会判断没匹配到【稀有掉落*0】这张图，所以就认为你刷到了稀有
> 
> 画质应该不影响二维的 UI
> 
> 应该是分辨率不同导致的

我以前用低画质失败，换成高画质就能成功。我记得你以前好像说过分辨率不影响

> 用的找图实现 理论上应该无需适配分辨率的

_Originally posted by @NateScarlet in https://github.com/NateScarlet/auto-dragalia/issues/6#issuecomment-479876830_

**Comment by NateScarlet** [comment]
因为找图默认相似是 0.9 就算找到了

但是找这个不知为啥 0.9 老是误判 我一路提高到 0.99

**Comment by youmei** [comment]
![0000](https://user-images.githubusercontent.com/8991918/55640021-ba963e00-5805-11e9-84f3-205b5bd4fba3.png)
这是我截的低画质下的稀有掉落图，红框里是你的源图片。
（似乎原图分辨率还不一样，我是2160*1080的手机）

**Comment by NateScarlet** [comment]
原来二维 UI 也会糊 试试这个

[main.auto.js.zip](https://github.com/NateScarlet/auto-dragalia/files/3048729/main.auto.js.zip)
