### ISSUE TITLE
查看是否有稀有掉落界面等待超时，似乎是因为无法识别到稀有图片

### ISSUE THREAD

**Issue by lgjhkd** [NateScarlet/auto-dragalia#12]
![Screenshot_2019-04-06-15-26-28-186_com nintendo z](https://user-images.githubusercontent.com/49181710/55666376-ac393800-5880-11e9-8377-c3b2f5087239.png)
![Screenshot_2019-04-06-15-27-22-100_org autojs aut](https://user-images.githubusercontent.com/49181710/55666377-ae02fb80-5880-11e9-9476-45ec8ffda65c.png)

**Comment by NateScarlet** [comment]
我添加下你的截图应该就能解决

**Comment by NateScarlet** [comment]
发现你的图竟然比我的扁 龙约怎么搞的 不同设备图还带拉伸的
