### ISSUE TITLE
刷稀有 判定全成功

### ISSUE THREAD

**Issue by ShallowAlex** [NateScarlet/auto-dragalia#126]
在使用刷稀有功能时，进图就会做一个判定（好像还判定已经处在第二关卡了？）在没有遇到怪前就会判定成功刷到稀有物品。猜测是图片适配问题（第一次用，也可能是我手法有问题？），图如下
![Screenshot_2019-09-05-10-57-46](https://user-images.githubusercontent.com/37401525/64355364-aadc8900-d033-11e9-9a63-1d81ef00fb9d.png)
![Screenshot_2019-09-05-10-58-00](https://user-images.githubusercontent.com/37401525/64355401-bb8cff00-d033-11e9-93bf-57e66aeee212.png)

## 设备信息

- 型号：OnePlus 6T
- 屏幕分辨率: 2340x1080
- 安卓版本：9
- Auto.js 版本: 4.0.5 Alpha

感谢您的帮助

**Comment by NateScarlet** [comment]
数字尺寸和已有素材差的有点大 龙约改了吗
等我我更新下素材

**Comment by NateScarlet** [comment]
开局就判定进第二关卡可能是什么东西把载入提示挡住了一下的原因

**Comment by NateScarlet** [comment]
试试 #127 里面最新的自动构建版本

**Comment by ShallowAlex** [comment]
自动构建的版本还是0稀有判定为成功
判定第二关的图片
![Screenshot_20190906-001637](https://user-images.githubusercontent.com/37401525/64359971-0874d380-d03c-11e9-9bfa-4116a6eedbc8.jpg)
![Screenshot_20190906-001642](https://user-images.githubusercontent.com/37401525/64359981-0e6ab480-d03c-11e9-855b-761f635a261c.jpg)
大佬这么晚还没睡吗？

**Comment by NateScarlet** [comment]
一共两个版本 上面版本的没处理消息提示的问题
你用的是9fec39的话就是消息显示时间超过2秒了

**Comment by ShallowAlex** [comment]
上边测试的9fec39版本
又测试了另一个版本，两个版本都依旧存在问题

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-dragalia/pull/127/commits/149d5db3abf7f1ae67f496351c1f49e9e45a4043

我把消息提示关了

**Comment by ShallowAlex** [comment]
进入关卡问题已解决
0稀有物品识别依旧成功

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-dragalia/pull/127/commits/15633e36cb8f1887b4b12f81c7c63ddd693d2ff0

之前素材没注意保存成 jpg 再截的 现在换成从原图截取的素材了
再不行我就不知道怎么搞了

**Comment by ShallowAlex** [comment]
辛苦了，还是不行

**Comment by NateScarlet** [comment]
发下日志

**Comment by NateScarlet** [comment]
顺便确认下脚本启动时是不是显示的 `Load assets: 1080x2340`

**Comment by ShallowAlex** [comment]
显示是1080x2340
![Screenshot_20190906-220651](https://user-images.githubusercontent.com/37401525/64434371-fdc94580-d0f2-11e9-9c54-be9f9b1831d1.jpg)
![Screenshot_20190906-220659](https://user-images.githubusercontent.com/37401525/64434359-f73ace00-d0f2-11e9-88ba-cc08033bc8ec.jpg)

**Comment by NateScarlet** [comment]
可以改下思路，不去找 `稀有物品x0`
而是在稀有物品下方区域找 `x0`
我本地测试好了再发上来

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-dragalia/pull/127/commits/becbfd66fe45d4b81237e382729e3a85424e3abe

本地测试成功，现在图片匹配精度要求降低了 应该能行

**Comment by ShallowAlex** [comment]
稀有x0识别成功了，掉落稀有物品还没遇到没测试
感谢维护
