### ISSUE TITLE
0.92 刷稀有超时，不稳定

### ISSUE THREAD

**Issue by nudgee28** [NateScarlet/auto-dragalia#13]
![Screenshot_2019-04-06-19-54-07-406_失落的龙约](https://user-images.githubusercontent.com/16789596/55669122-4e1f4b80-58a6-11e9-9f20-297d7c14d0fb.png)
![Screenshot_2019-04-06-19-55-04-617_失落的龙约](https://user-images.githubusercontent.com/16789596/55669123-4eb7e200-58a6-11e9-9d1a-f0897c524d77.png)

**Comment by NateScarlet** [comment]
你改成低或者高质量还会超时吗

**Comment by NateScarlet** [comment]
如果添加识别图片 需要稀有物品 x0 的截图

**Comment by nudgee28** [comment]
![Screenshot_2019-04-06-20-09-13-385_失落的龙约](https://user-images.githubusercontent.com/16789596/55669301-419bf280-58a8-11e9-9b16-ebb5c026e8da.png)
在测试低画质 看看有没有问题

**Comment by nudgee28** [comment]
。。。。好像经常刷到之手就卡住le了
![Screenshot_2019-04-06-20-22-29-877_失落的龙约](https://user-images.githubusercontent.com/16789596/55669426-c9cec780-58a9-11e9-84b4-76e3b4d0de88.png)

**Comment by NateScarlet** [comment]
日志有提示 `成功刷到稀有物品` 吗

或者你把整个日志截出来看看 auto.js 应用界面右上角可以看完整的日志

**Comment by nudgee28** [comment]
停止画面
![Screenshot_2019-04-06-21-02-34-475_失落的龙约](https://user-images.githubusercontent.com/16789596/55669878-5465f580-58af-11e9-9f38-fda69239b1cf.png)
![Screenshot_2019-04-06-21-02-16-030_Auto js](https://user-images.githubusercontent.com/16789596/55669879-54fe8c00-58af-11e9-86c5-f57c96af7955.png)

日志
![Screenshot_2019-04-06-21-02-16-030_Auto js](https://user-images.githubusercontent.com/16789596/55669882-5f208a80-58af-11e9-8855-173a17dfc73e.png)
![Screenshot_2019-04-06-21-02-34-475_失落的龙约](https://user-images.githubusercontent.com/16789596/55669884-6051b780-58af-11e9-926f-7c23aaed4e5d.png)

**Comment by NateScarlet** [comment]
你这个它中途点开过好几次菜单?

**Comment by NateScarlet** [comment]
[main.auto.js.zip](https://github.com/NateScarlet/auto-dragalia/files/3050504/main.auto.js.zip)

试下这个

**Comment by NateScarlet** [comment]
我也出现了一次类似的 

是打太快来不及点菜单... 总是被技能动画打断了

**Comment by NateScarlet** [comment]
看来这个问题就应该是战力太高 瞬间就把 boss 秒了

解决方法就是降倍速或者降战力

**Comment by nudgee28** [comment]
我试试看 谢谢了，
