### ISSUE TITLE
开始任务界面有概率无法识别开始任务按钮

### ISSUE THREAD

**Issue by lgjhkd** [NateScarlet/auto-dragalia#14]
![Screenshot_2019-04-06-17-09-18-167_com nintendo z](https://user-images.githubusercontent.com/49181710/55670088-87f64f00-58b2-11e9-897c-0bd96c0fae2e.png)

**Comment by NateScarlet** [comment]
什么版本? 换 0.9.2 还会出现吗

**Comment by NateScarlet** [comment]
这个可能是我超时设太短 我设的选完支援5秒内看不到开始任务按钮就算超时

**Comment by NateScarlet** [comment]
[main.auto.js.zip](https://github.com/NateScarlet/auto-dragalia/files/3050511/main.auto.js.zip)

试试这个超时改成了 10 秒的版本

**Comment by lgjhkd** [comment]
之前用的是092，我测试一下

**Comment by lgjhkd** [comment]
不行，还是有可能识别不出来

**Comment by NateScarlet** [comment]
那就是点了开始按钮但是没起作用

**Comment by lgjhkd** [comment]
辛苦了

**Comment by NateScarlet** [comment]
[main.auto.js.zip](https://github.com/NateScarlet/auto-dragalia/files/3050549/main.auto.js.zip)

只要没看到下一步按钮就会一直尝试点的版本

**Comment by lgjhkd** [comment]
嗯，应该可以了
