### ISSUE TITLE
无法重复战斗

### ISSUE THREAD

**Issue by XingWang95** [NateScarlet/auto-dragalia#144]
分辨率1080x1920

无法执行重复战斗
战斗中会触发支援技能，但不会龙化/龙化技能。结算页面就停住

小弟对TS不熟，是不是有采集图像的步骤需要做呢？
希望能稍微详细的指导一下。谢谢

**Comment by NateScarlet** [comment]
发下日志

**Comment by XingWang95** [comment]
## 描述

无法执行重复战斗
战斗中会触发支援技能，但不会龙化/龙化技能。结算页面就停住
其他操作例如自动喂龙也无法实现。可能是无法识别图片


## 重现

重现行为的步骤：

1. 开启autoJS和游戏
2. 选择任意功能
3. 点击到指定页面
4. 错误发生

## 预期行为

自动重复战斗，支援，龙化等
到龙的礼物页面点击功能实现自动喂龙

## 日志截图

https://imgur.com/a/kZhsHgP

## 设备信息

- 型号：[Sony F5121]
- 屏幕分辨率: [1080x1920]
- 安卓版本：[8.0.0]
- Auto.js 版本: [4.0.5 Alpha]
- auto-dragalia 版本: [0.12.0]

**Comment by NateScarlet** [comment]
应该是虚拟按键导致实际显示区域分辨率不是 1080x1920 所以图片识别不到

你参考 [/src/assets/images/1080x2160](https://github.com/NateScarlet/auto-dragalia/tree/master/src/assets/images/1080x2160) 放有用到的图片到 1080x1920 然后发一个 PR 应该能自动为你构建一版

或者等我有空拿你的截图弄一版来测试

而且看日志里有找到id为`2`的图片，代码里我找不到对应的地方

**Comment by XingWang95** [comment]
> 你参考 [/src/assets/images/1080x2160](https://github.com/NateScarlet/auto-dragalia/tree/master/src/assets/images/1080x2160) 放有用到的图片到 1080x1920 然后发一个 PR 应该能自动为你构建一版

请问一下PR指的是什么？pull request？
能详细解释一下步骤吗 
谢谢

**Comment by NateScarlet** [comment]
github上 PR 一般都是指的 pull request

在你 fork 的仓库做好修改 然后 `git push` 到 github  之后在仓库顶部应该会有创建PR的快捷方式

或者用 https://github.com/NateScarlet/auto-dragalia/pull/new/master
