### ISSUE TITLE
金币本稀有怪掉落物数量个人统计

### ISSUE THREAD

**Issue by lgjhkd** [NateScarlet/auto-dragalia#15]
* 1金袋n银袋  必定有四叶草
* 1金袋 必定是血核，没有幸运草(至少我没出过)
* 2金袋/2金袋n银袋 不确定，可能是两个血核也可能是一个血核加一个幸运草
* 3金袋 必定有幸运草

**Comment by nudgee28** [comment]
数量呢？我这大概1小时3个 不过我这不稳定
