### ISSUE TITLE
我用了4.x 版本的auto.js 也运行成功了，但是没有任何功能啊，运行后就帮我打开了游戏，就没有然后了。

### ISSUE THREAD

**Issue by valoya1130** [NateScarlet/auto-dragalia#158]

**Comment by NateScarlet** [comment]
你没有写着 `停止` 悬浮窗? 点击切换模式。
检查你是不是禁止了 auto.js 显示悬浮窗

不要每句话都开个新的 issue，用回复功能。

**Comment by valoya1130** [comment]
有写停止

NateScarlet <notifications@github.com> 于 2019年10月21日周一 下午10:08写道：

**Comment by valoya1130** [comment]
重复战斗功能怎么用啊，没反应。

NateScarlet <notifications@github.com> 于 2019年10月21日周一 下午10:08写道：

**Comment by NateScarlet** [comment]
进到战斗准备界面然后切换到 `重复战斗` 模式

准确来说是有  ![开始战斗按钮](/NateScarlet/auto-dragalia/raw/9d6d0a521e9aec40d00b52d5c2fc37f6d10b0d0a/src/assets/images/1080x2160/start-battle-button.png) 的界面

**Comment by valoya1130** [comment]
那刷稀有，是开哪种地图还是都可以

NateScarlet <notifications@github.com> 于 2019年10月22日周二 上午12:23写道：

**Comment by NateScarlet** [comment]
2个图的关卡应该都可以 不过一般是用金币任务

**Comment by valoya1130** [comment]
是这样嘛，然后点开始任务就行了嘛。他就会重复战斗。

NateScarlet <notifications@github.com> 于 2019年10月22日周二 上午12:26写道：

**Comment by NateScarlet** [comment]
它会帮你点开始任务，切换模式之后就不要操作了。同时操作会变成两指操作。

**Comment by valoya1130** [comment]
他没有自动点开始任务，是我还要等时间还是什么。

NateScarlet <notifications@github.com> 于 2019年10月22日周二 上午12:32写道：

**Comment by valoya1130** [comment]
是不是因为画质问题。

杨湛 <valoya1130@gmail.com> 于 2019年10月22日周二 上午12:33写道：

**Comment by NateScarlet** [comment]
发日志

参考 https://github.com/NateScarlet/auto-dragalia/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by valoya1130** [comment]
NateScarlet <notifications@github.com> 于 2019年10月22日周二 上午12:35写道：

**Comment by valoya1130** [comment]
其实功能我一个都没成功过。

杨湛 <valoya1130@gmail.com> 于 2019年10月22日周二 上午12:36写道：

**Comment by NateScarlet** [comment]
你什么都不发 光说不行我怎么帮你解决

**Comment by valoya1130** [comment]
我发了日志了呀

NateScarlet <notifications@github.com> 于 2019年10月22日周二 上午12:47写道：

**Comment by NateScarlet** [comment]
回复中没有

**Comment by NateScarlet** [comment]
有一条回复内容是空的 只有引用

**Comment by valoya1130** [comment]
现在收到了吗，大佬

NateScarlet <notifications@github.com> 于 2019年10月22日周二 上午12:50写道：

**Comment by NateScarlet** [comment]
你从 github 网页端回复吧，邮件回复应该是不支持附件
