### ISSUE TITLE
放弃，继续按钮无法识别

### ISSUE THREAD

**Issue by lgjhkd** [NateScarlet/auto-dragalia#16]
似乎我这边的字体都比ne你那边要宽一些
![Screenshot_2019-04-06-16-37-48-580_com nintendo z](https://user-images.githubusercontent.com/49181710/55671004-8da56200-58bd-11e9-8616-1322117c5147.png)
![Screenshot_2019-04-06-15-26-28-186_com nintendo z](https://user-images.githubusercontent.com/49181710/55671005-8f6f2580-58bd-11e9-80cd-dd0ecf01ef03.png)

**Comment by NateScarlet** [comment]
这差距识图应该可以兼容的 

你用 v0.10.1 试试 新版的日志有显示在找什么图

**Comment by NateScarlet** [comment]
你这个应该是稀有物品图标不识别吧 日志应该没有显示判定结果

你的图之前加过 用新版应该就能解决
