### ISSUE TITLE
autojs崩溃

### ISSUE THREAD

**Issue by lgjhkd** [NateScarlet/auto-dragalia#17]
脚本运行一段时间后，autojs会崩溃，无法看到之前的日志，使用的是0.8之后的版本，不确定是我手机的问题还是代码的问题

**Comment by NateScarlet** [comment]
autojs 4.0 还是 beta 版 就是有稳定性问题...

我也有时会崩

**Comment by NateScarlet** [comment]
你可以试试不用 2 倍速会不会更稳定
