### ISSUE TITLE
2倍速战斗，龙化速度慢

### ISSUE THREAD

**Issue by nudgee28** [NateScarlet/auto-dragalia#18]
能不能加快龙化的速度

**Comment by NateScarlet** [comment]
龙化速度指什么?

**Comment by nudgee28** [comment]
龙化技能条满了，但是要过上一会才会龙化，可能判断的时间有点慢，或者优先级不一样吧，主要是打高级本，龙化的快些，不容易死+打的快些。
PS：稀有解决了，关键就是拉低整个队伍的战力就好了，感谢：）之前主要是战力太快还没识别就结束了

**Comment by NateScarlet** [comment]
感觉上好像识别一张图要半秒左右

而且 Auto.js 好像不能并发识别

暂时没有优化的头绪

**Comment by NateScarlet** [comment]
把放技能的时候会重试连接服务器的行为优化了 但没多大效果 还是 7 秒左右一轮

之后试了下 Auto.js 的多线程, 一用就崩.....

**Comment by nudgee28** [comment]
感谢大佬，如果这样算了，问题是如果Auto.js 多线程能用，手机发热也会很严重的，最近刷我的坚果Pro2 已经很多次 提示过热了 ：（ 还是堆战力吧
