### ISSUE TITLE
English Translation? 英文翻译？

### ISSUE THREAD

**Issue by Harmonias** [NateScarlet/auto-dragalia#181]
（翻译成谷歌翻译）

## 您的功能请求是否与问题有关？ 请描述一下。

Hello, It's hard to use it and read errors with english language.
很难使用它并用英语阅读错误。

## 描述你想要的解决方案

Could you please make it able to detect Chinese/English and change output and image search depending on it? Not all images work with English.
使它能够检测中文/英文并根据其更改输出和搜索？ 并非所有图像都使用英语。

## 描述您考虑过的替代方案

Alternatively there would have to be a new repository, but it would be troublesome with updates.
另外，必须有一个新的存储库，但是更新会很麻烦。

## 附加背景

I don't think there is much I can say here.
我认为我在这里不能说太多。

**Comment by NateScarlet** [comment]
Could you collect english version of ![asset image](https://github.com/NateScarlet/auto-dragalia/tree/master/src/assets/images) for me?
Then i can improve my build process to create release for each set of asset images.

**Comment by NateScarlet** [comment]
Added i18n support and english translation. 
[auto-dragalia-78117408.zip](https://circleci.com/gh/NateScarlet/auto-dragalia/846/artifacts/0/home/circleci/project/artifacts/auto-dragalia-78117408.zip)

Please send pr with english asset, use folder name like `1080x1920-en` then you will got auto build for it.

**Comment by Harmonias** [comment]
Wow that was quick, thank you!
Does it need every picture or only the different ones?

Also my screenshot sizes are 1080x2264 so should I call the folder 1080x2264-en?

**Comment by NateScarlet** [comment]
only different ones, non existed image will fallback to use 1920x2160 asset.
and yes your should use that folder name.

**Comment by Harmonias** [comment]
Alright, I just need 4 more images. 
Can you maybe tell me where I can find those?

![image](https://user-images.githubusercontent.com/59190678/72528933-7f349f80-386c-11ea-8746-6c9444c97ec7.png)

**Comment by NateScarlet** [comment]
give-up-button-white: after stage failure
ok-button: confirm repeat battle with stamina
retry-button-blue:  maybe after stage failure due to timeout
retry-button-blue:  maybe after stage failure due to all member 0 hp
