### ISSUE TITLE
希望可以增加一个【重复战斗-自动吃蜂蜜版】的选项

### ISSUE THREAD

**Issue by youmei** [NateScarlet/auto-dragalia#19]
在点击【用体力续战】这张图之后
![repeat-with-stamina-button](https://user-images.githubusercontent.com/8991918/55681571-c51a1a00-5962-11e9-8bd3-bd1ca8530bb7.png)
如果若干次都没找到【ok】图片
![ok-button](https://user-images.githubusercontent.com/8991918/55681807-8cc80b00-5965-11e9-902c-91dcfaf8c2dc.png)
则尝试寻找【使用道具回复体力】这张图
![item-recover-stamina](https://user-images.githubusercontent.com/8991918/55681626-5e493080-5963-11e9-840c-d99bc3a49e03.png)
点击后，再寻找【加号】图片
![plus-button](https://user-images.githubusercontent.com/8991918/55681725-c2202900-5964-11e9-833f-f762284a1289.png)
点击三次（因为三种蜂蜜分别回10/20/30，最少回30，最多回90，只要体力最大值大于114的玩家，就不会浪费自回体）
最后再点击【关闭】
![close-button](https://user-images.githubusercontent.com/8991918/55681812-9a7d9080-5965-11e9-8fb9-589e6f28b393.png)
继续点击【ok】

**Comment by NateScarlet** [comment]
直接开刷前吃不就行了

**Comment by NateScarlet** [comment]
现在有双倍速 省不了多少体力 蜂蜜也不是无限多

所以我不会做这功能

你可以自己实现然后发 PR
