### ISSUE TITLE
自动喂食四叶草

### ISSUE THREAD

**Issue by nudgee28** [NateScarlet/auto-dragalia#20]
自动喂食四叶草，到MAX自动停止，可行吗？感谢

**Comment by youmei** [comment]
这样会造成好感度的浪费哦，没问题吗？
比如差100点到max，喂四叶草就浪费900点。

**Comment by nudgee28** [comment]
嗯嗯，那到29级吧，不浪费，最后一级自己点下

**Comment by NateScarlet** [comment]
现在有个问题，autojs会将信赖度28级和29级的图片识别混淆
![lv28-button](https://user-images.githubusercontent.com/8991918/55889638-52bc6a80-5bec-11e9-8aec-2d7eccda5365.png)
![lv29-button-big](https://user-images.githubusercontent.com/8991918/55889643-55b75b00-5bec-11e9-8108-342d014c4646.png)
脚本中，判断如果信赖度达到29级，throw一个error，但是在喂28级的时候，同样throw出这个error。

也尝试使用更小的图片，但是仍然不成功，不知道有什么好方法……
![lv29-button](https://user-images.githubusercontent.com/8991918/55890474-b4c99f80-5bed-11e9-8712-e3eee87f63c7.png)

_Originally posted by @youmei in https://github.com/NateScarlet/auto-dragalia/issues/21#issuecomment-481730652_

这个到这边讨论

你可以试试不找等级改成找所需信赖度 应该差异比 8 和 9 大

**Comment by youmei** [comment]
我想起来了，findImage默认threshold好像是0.9对吧。
改回0.99就可以了。

**Comment by NateScarlet** [comment]
0.99 的话还得处理 #12 那种跨分辨率识别不了的情况
