### ISSUE TITLE
稀有判定图片不识别

### ISSUE THREAD

**Issue by nudgee28** [NateScarlet/auto-dragalia#23]
![Screenshot_20190415_174942_com nintendo zaga](https://user-images.githubusercontent.com/16789596/56123912-0edcb300-5fa8-11e9-987f-d9f29b042e7f.jpg)
换了台手机，有没有黄袋子都识别为“成功刷到” 不知道是不是有拉伸或者其他的，能帮忙加下图片去程序里面
感谢

**Comment by nudgee28** [comment]
型号：huawei mate20 pro

**Comment by NateScarlet** [comment]
[auto-dragalia-dev.auto.js.zip](https://github.com/NateScarlet/auto-dragalia/files/3080098/auto-dragalia-dev.auto.js.zip)

请测试

**Comment by nudgee28** [comment]
谢谢，但是还是不行，好奇怪啊，难道华为对游戏图像做过优化加了锐度？

**Comment by NateScarlet** [comment]
你这是不是低画质

**Comment by NateScarlet** [comment]
顺便发下日志看看

**Comment by nudgee28** [comment]
影像品质（中） - 高画质
![Screenshot_20190415_215907_com nintendo zaga](https://user-images.githubusercontent.com/16789596/56138689-f1204580-5fc9-11e9-9494-4359fcdb5341.jpg)
![Screenshot_20190415_215938_org autojs autojs](https://user-images.githubusercontent.com/16789596/56138690-f1204580-5fc9-11e9-8edc-09f547c9ad4e.jpg)

**Comment by NateScarlet** [comment]
[auto-dragalia-dev.auto.js.zip](https://github.com/NateScarlet/auto-dragalia/files/3080536/auto-dragalia-dev.auto.js.zip)

发现这次的截图的 x0 和上个截图的 x0不太一样
试试这个

**Comment by NateScarlet** [comment]
另外 你这个截图不知为啥是JPG的 可能华为自动把图给你压缩了 然后识图的时候识的是没压缩的

**Comment by nudgee28** [comment]
还是不行，我找下第三方的截图试试 不知道行不行

**Comment by NateScarlet** [comment]
你可以试试 adb 

用 `adb exec-out screencap -p > screen.png` 可以截图

**Comment by nudgee28** [comment]
![screen](https://user-images.githubusercontent.com/16789596/56140774-22027980-5fce-11e9-98b4-bb396206c0b2.png)
用adb导出的

**Comment by nudgee28** [comment]
![screen](https://user-images.githubusercontent.com/16789596/56140805-2d55a500-5fce-11e9-88ee-e5d1bddd5c94.png)

**Comment by nudgee28** [comment]
显示图片已损坏奇怪了

**Comment by NateScarlet** [comment]
你本机能看吗

**Comment by nudgee28** [comment]
不行

**Comment by NateScarlet** [comment]
我用这命令能截 看来只能靠第三方软件了

**Comment by nudgee28** [comment]
导出的图片是有大小的，就是不能看

**Comment by nudgee28** [comment]
![ScreenshotExpert_2019-04-15-10-21-04](https://user-images.githubusercontent.com/16789596/56141153-d7353180-5fce-11e9-9a5a-9e1883a91742.png)
yong用第三方的

**Comment by nudgee28** [comment]
但是就400k比jpg的小醉了

**Comment by NateScarlet** [comment]
png本身就适合大片纯色的图 不知华为怎么想的

[auto-dragalia-dev.auto.js.zip](https://github.com/NateScarlet/auto-dragalia/files/3080653/auto-dragalia-dev.auto.js.zip)

试试这个

**Comment by nudgee28** [comment]
ok了 成功 我多测试 等有稀有看看 感谢 感谢

**Comment by nudgee28** [comment]
可以了 测试了没问题
