### ISSUE TITLE
支持 1200x1920 分辨率

### ISSUE THREAD

**Issue by dsmiling** [NateScarlet/auto-dragalia#25]
目前网络断开连接 选择重连会暂停流程
(我用的小米Pad基本所有图片都识别不了,我自己换了一套才可以

**Comment by NateScarlet** [comment]
什么流程 刷稀有会自动重连的

**Comment by dsmiling** [comment]
> 什么流程 刷稀有会自动重连的

读条的时候，有时候会网络不好 显示连接断开，回到主界面或者重连，这时候会卡好像没看到重连处理？

**Comment by NateScarlet** [comment]
我的意思是你选的什么任务 读的什么条 日志发一下

**Comment by dsmiling** [comment]
> 我的意思是你选的什么任务 读的什么条 日志发一下
> 
> Auto.js 右上角可以看日志

我改了一下检测图片好像可以了，之前测的是刷稀有流程

**Comment by NateScarlet** [comment]
应该是因为平板和手机分辨率差太多

**Comment by dsmiling** [comment]
> 应该是因为平板和手机分辨率差太多

是的。手机我倒没测试过

**Comment by dsmiling** [comment]
> 应该是因为平板和手机分辨率差太多

其实我觉得很多图片可以稍微改小一些识别区间，比如文字之类，会相对应提高机型的适配度

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-dragalia/blob/db6be6bc09c3293e127809bcb155e5335e7e2cb8/src/utils/image.ts#L30-L34

你可以试试在这里把找图阈值降低然后用现在的图跑

不过刷稀有不行 识别精度低就没法区分0和1
