### ISSUE TITLE
根据分辨率选择最合适的匹配图像

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-dragalia#26]
现在基本的匹配图像都是在我 2160x1080 的手机上截图的

平板上无法识别 #25 

现在的想法是

- [x] 在 assets/images 文件夹下面根据添加以分辨率命名的额外图像文件夹
- [x] 然后运行时根据设备屏幕分辨率使用不同的图像
- ~~应该需要支持额外图像包和主文件分离~~ webpack 分出来导入不了

**Comment by NateScarlet** [comment]
![Code_2019-04-16_23-06-34](https://user-images.githubusercontent.com/21083014/56221354-b3402180-609c-11e9-8f8b-68d8edf19c38.png)

@dsmiling 方便帮忙测试吗

发一下你那套 images 素材让我可以添加平板的分辨率

**Comment by dsmiling** [comment]
抱歉，我这几天没上git没看到。你现在已经自己添加完成了么？
如有需要我可以把我的素材提供给你

**Comment by NateScarlet** [comment]
你直接添加或者给我让我来加都行 
加到 assets/images 下面
最后还是要你才能测试 因为我没设备

**Comment by dsmiling** [comment]
那我提交一个PR吧。我看下你的分辨率设计思路
晚上改改提交一下，
我自己的小米pad4的分辨率是1200*1920
