### ISSUE TITLE
Bug::小米6使用炼草脚本时提示“请至关卡选择页面再开始”

### ISSUE THREAD

**Issue by lgjhkd** [NateScarlet/auto-dragalia#4]
已确认页面停留在金币本选择关卡界面，但运行脚本仍然提示“请至关卡选择页面再开始”

**Comment by NateScarlet** [comment]
截图看看 我找图找的是通关后得到的星

https://github.com/NateScarlet/auto-dragalia/blob/df8dcd99ab68d66f6494f29e79c658c796727dad/src/assets/images/level-select-button.png

不然就只能指定固定一关的名字了

**Comment by lgjhkd** [comment]
![Screenshot_2019-04-04-11-18-36-182_com nintendo z](https://user-images.githubusercontent.com/49181710/55529114-342d0f80-56d2-11e9-88f1-ae78b594bcaa.png)

**Comment by NateScarlet** [comment]
[auto-dragalia-issue4.auto.js.zip](https://github.com/NateScarlet/auto-dragalia/files/3043428/auto-dragalia-issue4.auto.js.zip)

试试这个 我换成了从你图上截的图 在我手机上测试能用

**Comment by NateScarlet** [comment]
话说是不是最低难度金币关也能炼草

那样直接指定用最低难度那关就行了 还能省体力

**Comment by lgjhkd** [comment]
一般来说都是在超级炼草的

**Comment by NateScarlet** [comment]
刷了一次高级稀有怪 但是没出幸运草

**Comment by lgjhkd** [comment]
只有金袋子会出幸运草，但也可能是血核。金币本初级中级高级超级的稀有怪都能出草
