### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by nudgee28** [NateScarlet/auto-dragalia#6]
1台锤子坚果pro2（root） 运行 显示 ![image](https://i.loli.net/2019/04/04/5ca5f34a90c59.jpg)

1台华为mate20 pro 运行 右上角显示 停止，然后 就显示 错误 error:Unknown task 停止 >#1
求解 是不是分辨率不对要调整
谢谢

**Comment by NateScarlet** [comment]
只支持 auto.js 4.0 以上的

因为用了老版本没有的 API

你得去 <https://github.com/hyb1996/Auto.js/releases> 下载 4.0

应用商店现在的应该都是 Auto.js 3

**Comment by NateScarlet** [comment]
> 求解 是不是分辨率不对要调整

用的找图实现 理论上应该无需适配分辨率的

**Comment by nudgee28** [comment]
感谢大佬，重新下了 新的 auto.js 可以了
