### ISSUE TITLE
半自动模式

### ISSUE THREAD

**Issue by nudgee28** [NateScarlet/auto-dragalia#71]

**Comment by NateScarlet** [comment]
自动战斗就是这样的啊

**Comment by nudgee28** [comment]
嗯少普攻击和技能点击（自动战斗是自动放技能的）

**Comment by NateScarlet** [comment]
感觉半自动不太合适 不能离开人那就直接人操作就完了
而且如果人和脚本同时操作应该会变成两点缩放

**Comment by nudgee28** [comment]
其实能全自动那最好，不过感觉有点困难，大多数多人本基本按照“向前移动2次，开始点击屏幕，普攻，技能满了放技能，龙槽满了，变龙，”一般中途不需要额外操作，基本就赢了，比如hard的raid或者帝国这些

> 而且如果人和脚本同时操作应该会变成两点缩放
这个没试过，不知道影响大不大

**Comment by nudgee28** [comment]
多人模式下的 移动寻怪 这个就要底层支持了吧，一般寻图判断我感觉也解决不了，我看过外挂的操作视频，那些是自动吸怪，不过那个太扯，也容易封号，还是简单些的就好了
