### ISSUE TITLE
网络环境较差时，“与服务器连接失败”弹窗会出现在【loading界面】以外的地方

### ISSUE THREAD

**Issue by youmei** [NateScarlet/auto-dragalia#9]
以下画面都会连接网络，网络较差时就会弹出错误弹窗，但代码中没有相应的处理逻辑：
1、选择助战人物时，
2、选择队伍时。
3、成功刷到稀有物品，继续打死boss后，刷出过关宝箱之前
4、没有刷到稀有物品，点击放弃后

我觉得应该在waitImage函数里try-catch的catch中增加一句tryClickImage(retryButton);

**Comment by NateScarlet** [comment]
说的是呢
